name: Lint CSS

on: [push, pull_request]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard --save-dev
      - name: Run Stylelint
        run: npx stylelint "assets/Styles/**/*.css"
