name: Mensaje Diario

on:
  schedule:
    - cron: '0 9 * * *' # Todos los días a las 9am UTC

jobs:
  diario:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Buenos días, este workflow se ejecuta diariamente."
