name: Lint JS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install ESLint
        run: npm install eslint --save-dev
      - name: Run ESLint
        run: npx eslint assets/JavaScript/**/*.js
