name: Repetir Mensaje

on:
  push:
    branches: [master]

jobs:
  repetir:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in {1..3}; do
            echo "Este es el mensaje número $i"
          done
